In [2]:
import numpy as np

a = np.load('/home/wcy/MADRL/maps/map_pool16.npy')
print(a.shape)
print(a[0])
print(a[1])

(10, 16, 16)
[[ 0  0 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0  0  0  0  0  0  0]
 [ 0  0 -1 -1 -1 -1  0 -1 -1 -1 -1  0  0  0  0  0]
 [-1 -1 -1 -1 -1 -1  0  0  0 -1 -1  0  0  0  0  0]
 [-1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0 -1 -1  0]
 [-1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0 -1 -1  0]
 [-1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0  0  0 -1 -1  0 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0  0 -1 -1  0 -1 -1]
 [ 0  0  0  0  0  0  0  0  0 -1 -1  0  0  0  0  0]
 [ 0 -1 -1 -1 -1 -1 -1  0  0 -1 -1  0  0  0  0  0]
 [ 0 -1 -1 -1 -1 -1 -1  0  0 -1 -1  0  0  0  0  0]
 [ 0  0  0 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 -1 -1  0  0  0  0]
 [ 0  0  0  0  0 -1 -1  0  0  0 -1 -1  0 -1 -1 -1]
 [ 0  0  0  0  0 

In [3]:
b = map(int, '10,10'.split(','))
print('10,10'.split(','))

['10', '10']


In [9]:
Map = np.zeros((2, 5, 5), dtype=np.int32);
Map[0][2,2] = 2
Map[1][2,2] = 2

with open('maptest.npy', 'wb') as f:
    np.save(f, Map)


In [10]:
a = np.load('./maptest.npy');
print(a)
print(a.shape)


[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 2 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 2 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
(2, 5, 5)
